/**
 * Colors extracted from the Ninja Adventure asset pack.
 * This is the only palette available in the pixel editor (design section-2.3).
 * Generated by scripts/extract-palette.ts -- regenerate when tilesets are available.
 *
 * PLACEHOLDER: These are representative pixel-art colors. Re-run extraction
 * with actual Ninja Adventure tilesets for the final palette.
 */
export const PALETTE: readonly string[] = [
  "#000000", "#1A1A2E", "#16213E", "#0F3460", "#1B4965", "#2C6E49",
  "#1B998B", "#2EC4B6", "#59C9A5", "#95D5B2", "#D8F3DC", "#FFFFFF",
  "#F8F9FA", "#E9ECEF", "#DEE2E6", "#CED4DA", "#ADB5BD", "#6C757D",
  "#495057", "#343A40", "#212529", "#533483", "#7B2D8E", "#9B5DE5",
  "#C77DFF", "#E94560", "#FF6B6B", "#FF8E72", "#FFA07A", "#FFB347",
  "#FFCB77", "#FFE66D", "#F4D35E", "#FFF1C9", "#F0E68C", "#7AE582",
  "#4CB944", "#2D6A4F", "#1B4332", "#081C15", "#3A0CA3", "#4361EE",
  "#4CC9F0", "#7209B7", "#F72585", "#B5179E", "#560BAD", "#480CA8",
  "#D4A373", "#C68B59", "#A47148", "#8B5E34", "#6F4518", "#5C3D2E",
  "#8D6346", "#A0785A", "#C09E7B", "#DEB887", "#F5DEB3", "#FAEBD7",
  "#8B4513", "#A0522D", "#CD853F", "#D2691E", "#704214", "#3E2723",
] as const;

/** Transparent "color" used for empty pixels. */
export const TRANSPARENT = "";
